name: Date print Output

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-date-command:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass tmux

      - name: Wait 45 seconds before proceeding
        run: |
          echo "Waiting 45 seconds..."
          sleep 45

      - name: Verify tmux installation and list sessions on remote
        run: |
          echo "Verifying tmux installation and listing sessions on the remote server..."
          sshpass -p "segfault" ssh \
            -o StrictHostKeyChecking=no \
            -o "SetEnv SECRET=TnouJyPIWNrTiKeOMxWSLtqh" \
            root@lulz.segfault.net "tmux --help; tmux list-sessions"

      - name: Run date command in new tmux window and capture its output
        run: |
          echo "Creating new tmux window to run 'date' and capturing output..."
          sshpass -p "segfault" ssh \
            -o StrictHostKeyChecking=no \
            -o "SetEnv SECRET=TnouJyPIWNrTiKeOMxWSLtqh" \
            root@lulz.segfault.net "
              # Create a new window named 'date-run' in the 'segauto' session that runs date and waits 5 seconds
              tmux new-window -t segauto -n date-run 'date; sleep 5';
              # Give a moment for the command to complete
              sleep 6;
              echo '--- Captured date output ---';
              # Capture and print the output of the new window
              tmux capture-pane -pt segauto:date-run;
              # Clean up by closing the temporary window
              tmux kill-window -t segauto:date-run
            "
