name: Date Command Scheduler with Captured Output

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-date-command:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass tmux

      - name: Wait 45 seconds before proceeding
        run: |
          echo "Waiting 45 seconds..."
          sleep 45

      - name: Verify tmux installation and list sessions on remote
        run: |
          echo "Verifying tmux installation and listing sessions on the remote server..."
          sshpass -p "segfault" ssh \
            -o StrictHostKeyChecking=no \
            -o "SetEnv SECRET=TnouJyPIWNrTiKeOMxWSLtqh" \
            root@lulz.segfault.net "tmux --help; tmux list-sessions"

      - name: Create tmux window, run date, capture output, and remove window
        run: |
          echo "Creating a new tmux window to run 'date' and capture its output..."
          sshpass -p "segfault" ssh \
            -o StrictHostKeyChecking=no \
            -o "SetEnv SECRET=TnouJyPIWNrTiKeOMxWSLtqh" \
            root@lulz.segfault.net "
              tmux new-window -d -n date-run 'date; sleep 10';
              sleep 11;
              echo '--- Captured date output ---';
              tmux capture-pane -pt segauto:date-run;
              tmux kill-window -t segauto:date-run
            "
