name: Date Command Scheduler with New Window and Output Capture

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-date-command:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass tmux

      - name: Wait 45 seconds before proceeding
        run: |
          echo "Waiting 45 seconds..."
          sleep 45

      - name: Verify tmux installation and list sessions on remote
        run: |
          echo "Verifying tmux installation and listing sessions on the remote server..."
          sshpass -p "segfault" ssh \
            -o StrictHostKeyChecking=no \
            -o "SetEnv SECRET=TnouJyPIWNrTiKeOMxWSLtqh" \
            root@lulz.segfault.net "tmux --help; tmux list-sessions"

      - name: Create new tmux window to run date command and Capture Output
        run: |
          echo "Creating new window in segauto session to run the 'date' command and capturing output..."
          DATE_OUTPUT=$(sshpass -p "segfault" ssh \
            -o StrictHostKeyChecking=no \
            -o "SetEnv SECRET=TnouJyPIWNrTiKeOMxWSLtqh" \
            root@lulz.segfault.net "tmux new-window -t segauto -n date-run 'date; sleep 5'; tmux capture-pane -pS -3 -t segauto:date-run")

          echo "-------------------- Date Command Output --------------------"
          echo "$DATE_OUTPUT"
          echo "-------------------------------------------------------------"
