name: Segfault Shell Command Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-segfault-command:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass tmux

      - name: Run random command on segfault shell
        env:
          SEGFAULT_SECRET: ${{ secrets.SEGFAULT_SECRET }}
          SEGFAULT_SERVER: ${{ secrets.SEGFAULT_SERVER }}
        run: |
          # Define list of simple commands and pick one using $RANDOM
          commands=("whoami" "pwd" "w" "lscpu" "uptime")
          command=${commands[$RANDOM % ${#commands[@]}]}
          echo "Selected command: $command"
          
          # Build the remote command as a single-line string.
          REMOTE_CMD="SESSION_NAME='segauto'; if tmux has-session -t \"\$SESSION_NAME\" 2>/dev/null; then echo 'Attaching to existing tmux session \$SESSION_NAME'; else echo 'Creating new tmux session \$SESSION_NAME'; tmux new-session -d -s \"\$SESSION_NAME\"; fi; tmux send-keys -t \"\$SESSION_NAME\" \"$command\" Enter; sleep 2; tmux detach -s \"\$SESSION_NAME\""
          
          echo "Executing remote command on segfault server..."
          sshpass -p "segfault" ssh -o StrictHostKeyChecking=no -o "SetEnv SECRET=${SEGFAULT_SECRET}" root@${SEGFAULT_SERVER} "$REMOTE_CMD"
