name: Segfault Shell Command Scheduler #file path .github/workflows/segfault-scheduler.yml

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes

jobs:
  run-segfault-command:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass tmux

      - name: Execute remote command and send email
        env:
          SEGFAULT_SECRET: ${{ secrets.SEGFAULT_SECRET }}
          SEGFAULT_SERVER: ${{ secrets.SEGFAULT_SERVER }}
          MAILGUN_API_KEY: ${{ secrets.MAILGUN_API_KEY }}
          MAILGUN_DOMAIN: ${{ secrets.MAILGUN_DOMAIN }}
        run: |
          # Define a list of non-critical commands
          NON_CRITICAL_COMMANDS=("ls -la" "uptime" "df -h" "free -m" "echo 'Hello from segNetherfault'" "date" "free -h" "ps aux" "netstat -tuln" "lsb_release -a" "uname -a" "whoami" "pwd" "w" "cat /proc/cpuinfo" "cat /proc/meminfo" "lscpu")
          
          # Choose one command randomly
          RANDOM_INDEX=$((RANDOM % ${#NON_CRITICAL_COMMANDS[@]}))
          SELECTED_COMMAND=${NON_CRITICAL_COMMANDS[$RANDOM_INDEX]}
          echo "Selected command: $SELECTED_COMMAND"
          
          # SSH into segfault server using sshpass (auto-enter password "segfault")
          sshpass -p "segfault" ssh -o StrictHostKeyChecking=no -o "SetEnv SECRET=${SEGFAULT_SECRET}" root@${SEGFAULT_SERVER} <<EOF
# Create (or attach to) a tmux session named "mysession"
tmux new-session -d -s mysession || true

# Send the selected command into the tmux session
tmux send-keys -t mysession "${SELECTED_COMMAND}" C-m

# Allow some time for the command to execute
sleep 5

# Capture the output from the tmux pane
OUTPUT=\$(tmux capture-pane -pt mysession)

# Generate timestamp in UTC+05:30 (Asia/Kolkata) in 12hr format with AM/PM, Date and Day
TIMESTAMP=\$(TZ=Asia/Kolkata date "+%I:%M:%S %p, %d-%m-%Y (%A)")

# Prepare the email content
EMAIL_TEXT="Timestamp: \${TIMESTAMP}\nCommand: ${SELECTED_COMMAND}\nOutput:\n\${OUTPUT}"

# Send email via Mailgun API
curl -s --user "api:${MAILGUN_API_KEY}" "https://api.mailgun.net/v3/${MAILGUN_DOMAIN}/messages" \\
  -F from="Mailgun Sandbox <postmaster@${MAILGUN_DOMAIN}>" \\
  -F to="Mari Skripper <skripper9090@tuta.io>" \\
  -F subject="Command Execution Confirmation" \\
  -F text="\${EMAIL_TEXT}"

# Detach the tmux session
tmux detach -s mysession
EOF

