name: Date Command Scheduler with Output Capture

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:
  run-date-command:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass tmux

      - name: Wait 25 seconds before proceeding
        run: |
          echo "Waiting 25 seconds..."
          sleep 25

      - name: Verify tmux installation and list sessions on remote
        run: |
          echo "Verifying tmux installation and listing sessions on the remote server..."
          sshpass -p "segfault" ssh \
            -o StrictHostKeyChecking=no \
            -o "SetEnv SECRET=TnouJyPIWNrTiKeOMxWSLtqh" \
            root@lulz.segfault.net "tmux --help; tmux list-sessions"

      - name: Create and capture date command output
        run: |
          echo "Creating new window and capturing date command output..."
          sshpass -p "segfault" ssh \
            -o StrictHostKeyChecking=no \
            -o "SetEnv SECRET=TnouJyPIWNrTiKeOMxWSLtqh" \
            root@lulz.segfault.net "tmux new-window -t segauto -n date-run 'date && sleep 2'; \
            sleep 1; \
            tmux capture-pane -p -t segauto:date-run"
